version: '3.7'
services:
  upstream:
    build:
      context: ./
      dockerfile: ./samples/Docker.Web/Dockerfile
    ports:
     - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApplicationInsights:InstrumentationKey
      - ApplicationInsights:TelemetryChannel:StorageFolder=/tmp/app-logs
      - DownstreamService:BaseAddress=http://downtream/
  downtream:
    build:
      context: ./
      dockerfile: ./samples/Docker.Downstream/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApplicationInsights:InstrumentationKey
      - ApplicationInsights:TelemetryChannel:StorageFolder=/tmp/app-logs
